stages:
  - scan
  - build
  - test

build_app:
  stage: build
  image: python:3.11-slim
  script:
    - pip install -q -r requirements.txt
    - python -m compileall main.py

scan-code:
  stage: scan
  image: sonarsource/sonar-scanner-cli
  script:
    - sonar-scanner -Dsonar.projectKey=SonarCubeTest -Dsonar.sources=.

test_app:
  stage: test
  image: python:3.11-slim
  script:
    - pip install -q -r requirements.txt
    - pytest -q
